### ISSUE TITLE
Conflicting peer dependency

### ISSUE THREAD

**Issue by DePasqualeOrg** [umaranis/svelte-lexical#3]
I'm trying to integrate this package into an existing SvelteKit project, but am running into several roadblocks along the way. When I update the dependencies with `npx ncu -u && npm i`, I get the following errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: svelte-lexical@0.1.2-beta.2
npm ERR! Found: @lexical/clipboard@0.2.2
npm ERR! node_modules/@lexical/clipboard
npm ERR!   @lexical/clipboard@"0.2.9" from the root project
npm ERR!   peer @lexical/clipboard@"0.2.2" from @lexical/plain-text@0.2.2
npm ERR!   node_modules/@lexical/plain-text
npm ERR!     @lexical/plain-text@"^0.2.9" from the root project
npm ERR!   1 more (@lexical/rich-text)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @lexical/clipboard@"0.2.9" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: lexical@0.2.9
npm ERR! node_modules/lexical
npm ERR!   peer lexical@"0.2.9" from @lexical/clipboard@0.2.9
npm ERR!   node_modules/@lexical/clipboard
npm ERR!     @lexical/clipboard@"0.2.9" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /<redacted>/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /<redacted>/.npm/_logs/2022-05-31T09_49_08_184Z-debug-0.log
```

**Comment by umaranis** [comment]
Hi @DePasqualeOrg ,
I have committed a working version of svelte-lexical in svelte-kit project. Check it out under `demos/sveltekit` folder.

Mainly the errors are due to different build systems I guess (rollup vs vite). Two issues that I had to resolve were:
- Vite wants to explicitly include lexical dependencies. It is not picking them up from svelte-lexical dependencies. Therefore, you can see the change in package.json with lexical dependencies included in svelte-kit project.
- Faced some issues with the imports. Had to change some import-related code in svelte-lexical package.

Let me know how you go with it. Thanks.

**Comment by DePasqualeOrg** [comment]
Fantastic, thank you!
